### ISSUE TITLE
Server still crashes with essentials-module-datapacks

### ISSUE THREAD

**Issue by CamperSamu** [NyliumMC/Essentials#49] opened 2020-07-23 13:09 UTC
**Information**
- Minecraft Version: 1.16.1 server
- Fabric API Version: 1.15.1 b380
- OS: PebbleHost server (Linux? - ???)
- Other installed mods: Full EfF package 0.2.4, ViaFabric (+ViaVer, ViaBack, ProtocolSupp), Carpet, Tree Chopper, Vanilla death chest, silk spawners, eldrich mobs, simplex, river redux, ecotones, cave biomes, mo'structures, repurposed structures, rpgstats, tinytweaks, PolyMC, OfflineSkins, CustomSkinLoader, nbtcrafting, mobs attempt parkour, photoallergic creeper, prone, TCP, lithium, phosphor, hot furnaces, compressed blocks, boatfix, armorstandutils, better signs and frames. (I may have forgot to add some mods to the list)

**Describe the issue**
Server still crashes with essentials-module-datapacks

**Crash/Error logs**
https://hastebin.com/usinikuzor.sql

**To Reproduce**
Start the server with essentials-module-datapacks + full EfF

**Expected behavior**
The server should boot

**Comment by martmists** [comment] 2020-07-23 13:14
Duplicate of #48

**Closed by martmists** 2020-07-23 13:14 UTC
